### ISSUE TITLE
Add filter functionality to `/index/` page

### ISSUE THREAD

**Issue by alecmarcus** [Upstatement/ups-public-library#16]
Depends on #15

**Comment by bchiang7** [comment]
What kind of filtering are you thinking of here?

**Comment by alecmarcus** [comment]
> What kind of filtering are you thinking of here?

First thing that comes to mind is to filter by [topic tag (`html`, `css`, etc).](https://github.com/Upstatement/ups-public-library/blob/3b8a0c1fd9b585bfaca2d84df4b97bbb6e6b7d32/src/entries/html-elements.md#L6)

As we add content, we plan to start tagging with levels of difficulty from 1 - 4 (Foundational, Intermediate, Advanced, Master), and I'd like for users to be able to filter by those as well. They would be set by adding a tag as well.

Something else that comes to mind is to be able to filter by type, eg, only show entries / series / collections. If we were to implement that, only showing entries would show _all_ entries, including ones that are in series / collections. However, I'm unsure of how useful that would be, so if it's complex we can hold off.

**Comment by alecmarcus** [comment]
Closing for now, we may revisit later
